module.exports = {
  restaurants: {
    RECEIVE_RESTAURANTS: 'RECEIVE_RESTAURANTS',
    SET_SERVICE_AREA: 'SET_SERVICE_AREA'
  },
  auth: {
    AUTHENTICATE: 'AUTHENTICATE',
    UNAUTHENTICATE: 'UNAUTHENTICATE'
  },
  common: {
    modals: {
      OPEN_MODAL: 'OPEN_MODAL',
      CLOSE_MODAL: 'CLOSE_MODAL'
    },
    pagination: {
      SWITCH_PAGE: 'SWITCH_PAGE',
      SET_TOTAL_PAGES: 'SET_TOTAL_PAGES'
    },
    forms: {
      ADD_INPUT: 'ADD_INPUT',
      REMOVE_INPUT: 'REMOVE_INPUT',
      UPDATE_INPUT: 'UPDATE_INPUT',
      UPDATE_FORM: 'UPDATE_FORM',
      REQUEST_SUBMIT_FORM: "REQUEST_SUBMIT_FORM",
      RESET_FORM: "RESET_FORM",
    },
    notifications: {
      ERROR_NOTICE: 'ERROR_NOTICE',
      SUCCESS_NOTICE: 'SUCCESS_NOTICE',
      DISMISS_NOTICE: 'DISMISS_NOTICE'
    },
    spinner: {
      LAUNCH: "LAUNCH_SPINNER",
      CLOSE: "CLOSE_SPINNER"
    }
  }
}