var keyMirror                 = require('keymirror');
var ApplicationConstants      = require('./ApplicationConstants.js');

module.exports = {
  SUCCESS_CREATE : 'DATA HAS BEEN SAVED.',
  SUCCESS_UPDATE : 'DATA HAS BEEN UPDATED.',
  SUCCESS_DELETE : 'DATA HAS BEEN DELETED.',
  SUCCESS_UPLOAD : 'IMAGE HAS BEEN UPLOADED.',
  SUCCESS_RESET_REST_IMAGE_TO_BRAND: 'SUCCESSFULLY RESET RESTAURANT IMAGE TO BRAND IMAGE',
  FAILED_TO_CONNECT: 'FAILED TO CONNECT TO SERVER',
  CATEGORY_DELETE_SUCCESS: 'CATEGORY HAS BEEN DELETED',
  CATEGORY_DELETE_FAILURE: 'FAILED TO DELETE CATEGORY',
  RESET_REST_IMAGE_TO_BRAND_FAILURE: 'FAILED TO RESET RESTAURANT IMAGE TO BRAND IMAGE',

  ActionTypes: keyMirror({
    REVOKE_NOTICE:    null,
    INVOKE_NOTICE:    null
  })
};
